services:
  backend:
    image: 'ghcr.io/suny-poly-cs-club/attendance-app-backend'
    build: '.'
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - '.env'
    depends_on:
      migrate:
        condition: 'service_completed_successfully'

      postgres:
        condition: 'service_healthy'

  migrate:
    image: 'ghcr.io/suny-poly-cs-club/attendance-app-backend-migrate'
    build:
      context: .
      dockerfile: ./docker/migrate/Dockerfile
    command: 'up'
    environment:
      DATABASE_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable'
      DBMATE_WAIT: 'true'
    env_file:
      - '.env'
    depends_on:
      postgres:
        condition: 'service_healthy'

  postgres:
    image: 'postgres:16'
    environment:
      TZ: 'America/New_York'
      PGTZ: 'America/New_York'
      PGUSER: '${POSTGRES_USER}'
    env_file:
      - '.env'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '${POSTGRES_DB}']
      interval: '10s'
      timeout: '5s'
      retries: 5

volumes:
  postgres_data:
